
		*Node_Alias
		*Node_RangeVar
		*Node_TableFunc
		*Node_IntoClause
		*Node_Var
		*Node_Param
		*Node_Aggref
		*Node_GroupingFunc
		*Node_WindowFunc
		*Node_SubscriptingRef
		*Node_FuncExpr
		*Node_NamedArgExpr
		*Node_OpExpr
		*Node_DistinctExpr
		*Node_NullIfExpr
		*Node_ScalarArrayOpExpr
		*Node_BoolExpr
		*Node_SubLink
		*Node_SubPlan
		*Node_AlternativeSubPlan
		*Node_FieldSelect
		*Node_FieldStore
		*Node_RelabelType
		*Node_CoerceViaIo
		*Node_ArrayCoerceExpr
		*Node_ConvertRowtypeExpr
		*Node_CollateExpr
		*Node_CaseExpr
		*Node_CaseWhen
		*Node_CaseTestExpr
		*Node_ArrayExpr
		*Node_RowExpr
		*Node_RowCompareExpr
		*Node_CoalesceExpr
		*Node_MinMaxExpr
		*Node_SqlvalueFunction
		*Node_XmlExpr
		*Node_JsonFormat
		*Node_JsonReturning
		*Node_JsonValueExpr
		*Node_JsonConstructorExpr
		*Node_JsonIsPredicate
		*Node_NullTest
		*Node_BooleanTest
		*Node_CoerceToDomain
		*Node_CoerceToDomainValue
		*Node_SetToDefault
		*Node_CurrentOfExpr
		*Node_NextValueExpr
		*Node_InferenceElem
		*Node_TargetEntry
		*Node_RangeTblRef
		*Node_JoinExpr
		*Node_FromExpr
		*Node_OnConflictExpr
		*Node_Query
		*Node_TypeName
		*Node_ColumnRef
		*Node_ParamRef
		*Node_AExpr
		*Node_TypeCast
		*Node_CollateClause
		*Node_RoleSpec
		*Node_FuncCall
		*Node_AStar
		*Node_AIndices
		*Node_AIndirection
		*Node_AArrayExpr
		*Node_ResTarget
		*Node_MultiAssignRef
		*Node_SortBy
		*Node_WindowDef
		*Node_RangeSubselect
		*Node_RangeFunction
		*Node_RangeTableFunc
		*Node_RangeTableFuncCol
		*Node_RangeTableSample
		*Node_ColumnDef
		*Node_TableLikeClause
		*Node_IndexElem
		*Node_DefElem
		*Node_LockingClause
		*Node_XmlSerialize
		*Node_PartitionElem
		*Node_PartitionSpec
		*Node_PartitionBoundSpec
		*Node_PartitionRangeDatum
		*Node_PartitionCmd
		*Node_RangeTblEntry
		*Node_RtepermissionInfo
		*Node_RangeTblFunction
		*Node_TableSampleClause
		*Node_WithCheckOption
		*Node_SortGroupClause
		*Node_GroupingSet
		*Node_WindowClause
		*Node_RowMarkClause
		*Node_WithClause
		*Node_InferClause
		*Node_OnConflictClause
		*Node_CtesearchClause
		*Node_CtecycleClause
		*Node_CommonTableExpr
		*Node_MergeWhenClause
		*Node_MergeAction
		*Node_TriggerTransition
		*Node_JsonOutput
		*Node_JsonKeyValue
		*Node_JsonObjectConstructor
		*Node_JsonArrayConstructor
		*Node_JsonArrayQueryConstructor
		*Node_JsonAggConstructor
		*Node_JsonObjectAgg
		*Node_JsonArrayAgg
		*Node_RawStmt
		*Node_InsertStmt
		*Node_DeleteStmt
		*Node_UpdateStmt
		*Node_MergeStmt
		//*Node_SelectStmt
		*Node_SetOperationStmt
		*Node_ReturnStmt
		*Node_PlassignStmt
		*Node_CreateSchemaStmt
		*Node_AlterTableStmt
		*Node_ReplicaIdentityStmt
		*Node_AlterTableCmd
		*Node_AlterCollationStmt
		*Node_AlterDomainStmt
		*Node_GrantStmt
		*Node_ObjectWithArgs
		*Node_AccessPriv
		*Node_GrantRoleStmt
		*Node_AlterDefaultPrivilegesStmt
		*Node_CopyStmt
		*Node_VariableSetStmt
		*Node_VariableShowStmt
		*Node_CreateStmt
		*Node_Constraint
		*Node_CreateTableSpaceStmt
		*Node_DropTableSpaceStmt
		*Node_AlterTableSpaceOptionsStmt
		*Node_AlterTableMoveAllStmt
		*Node_CreateExtensionStmt
		*Node_AlterExtensionStmt
		*Node_AlterExtensionContentsStmt
		*Node_CreateFdwStmt
		*Node_AlterFdwStmt
		*Node_CreateForeignServerStmt
		*Node_AlterForeignServerStmt
		*Node_CreateForeignTableStmt
		*Node_CreateUserMappingStmt
		*Node_AlterUserMappingStmt
		*Node_DropUserMappingStmt
		*Node_ImportForeignSchemaStmt
		*Node_CreatePolicyStmt
		*Node_AlterPolicyStmt
		*Node_CreateAmStmt
		*Node_CreateTrigStmt
		*Node_CreateEventTrigStmt
		*Node_AlterEventTrigStmt
		*Node_CreatePlangStmt
		*Node_CreateRoleStmt
		*Node_AlterRoleStmt
		*Node_AlterRoleSetStmt
		*Node_DropRoleStmt
		*Node_CreateSeqStmt
		*Node_AlterSeqStmt
		*Node_DefineStmt
		*Node_CreateDomainStmt
		*Node_CreateOpClassStmt
		*Node_CreateOpClassItem
		*Node_CreateOpFamilyStmt
		*Node_AlterOpFamilyStmt
		*Node_DropStmt
		*Node_TruncateStmt
		*Node_CommentStmt
		*Node_SecLabelStmt
		*Node_DeclareCursorStmt
		*Node_ClosePortalStmt
		*Node_FetchStmt
		*Node_IndexStmt
		*Node_CreateStatsStmt
		*Node_StatsElem
		*Node_AlterStatsStmt
		*Node_CreateFunctionStmt
		*Node_FunctionParameter
		*Node_AlterFunctionStmt
		*Node_DoStmt
		*Node_InlineCodeBlock
		*Node_CallStmt
		*Node_CallContext
		*Node_RenameStmt
		*Node_AlterObjectDependsStmt
		*Node_AlterObjectSchemaStmt
		*Node_AlterOwnerStmt
		*Node_AlterOperatorStmt
		*Node_AlterTypeStmt
		*Node_RuleStmt
		*Node_NotifyStmt
		*Node_ListenStmt
		*Node_UnlistenStmt
		*Node_TransactionStmt
		*Node_CompositeTypeStmt
		*Node_CreateEnumStmt
		*Node_CreateRangeStmt
		*Node_AlterEnumStmt
		*Node_ViewStmt
		*Node_LoadStmt
		*Node_CreatedbStmt
		*Node_AlterDatabaseStmt
		*Node_AlterDatabaseRefreshCollStmt
		*Node_AlterDatabaseSetStmt
		*Node_DropdbStmt
		*Node_AlterSystemStmt
		*Node_ClusterStmt
		*Node_VacuumStmt
		*Node_VacuumRelation
		*Node_ExplainStmt
		*Node_CreateTableAsStmt
		*Node_RefreshMatViewStmt
		*Node_CheckPointStmt
		*Node_DiscardStmt
		*Node_LockStmt
		*Node_ConstraintsSetStmt
		*Node_ReindexStmt
		*Node_CreateConversionStmt
		*Node_CreateCastStmt
		*Node_CreateTransformStmt
		*Node_PrepareStmt
		*Node_ExecuteStmt
		*Node_DeallocateStmt
		*Node_DropOwnedStmt
		*Node_ReassignOwnedStmt
		*Node_AlterTsdictionaryStmt
		*Node_AlterTsconfigurationStmt
		*Node_PublicationTable
		*Node_PublicationObjSpec
		*Node_CreatePublicationStmt
		*Node_AlterPublicationStmt
		*Node_CreateSubscriptionStmt
		*Node_AlterSubscriptionStmt
		*Node_DropSubscriptionStmt
		*Node_Integer
		*Node_Float
		*Node_Boolean
		*Node_String_
		*Node_BitString
		*Node_List
		*Node_IntList
		*Node_OidList
		*Node_AConst